#+LaTeX_HEADER: \usepackage[spanish]{babel}
#+LANGUAGE: es
#+Latex_class: koma-report
#+AUTHOR: Niv Sardi <niv.sardi@unq.edu.ar>, Vladimir di Fiore Prieto <vdifiore@gmail.com>
#+TITLE: HackaTren 
* Resumen
EL HackaTren toma como punto de partida al tren como actor en la
comunicación y la vida socio económica de los pueblos que conecta en su
recorrido para sumar una propuesta cultural y educativa centrada en el
conocimiento libre y la transferencia tecnológica.

Es sobre esta base que se quiere potenciar la re apertura del ramal Buenos
Aires Bariloche con un tren del conocimiento, que a forma de catalizador de
la interacción entre los pueblos, irá dejando diferentes experiencias a lo
largo de todo su recorrido interactuando con los habitantes de las
estaciones donde se realicen actividades fuera del tren.

El viaje y sus paradas será registrado por la productora Metropolis Films de
forma voluntaria y bajo una licencia libre para su posterior uso.
Todos los desarrollos serán liberados con licencia libre.

* Actividad central
Durante todo el recorrido del tren se utilizara un vagón para que los y las
participantes del #Hackatren puedan trabajar en sus proyectos de desarrollo
a lo largo del recorrido del tren. Estos desarrollos serán publicados una
vez finalizado el viaje. (las mismas se postularan previo a la salida del
tren en un dahsboard donde podrán verse propuestas de los participantes y
del Ministerio de Interior y Transporte )

El objetivo es hacer un relevamiento de los problemas reales (tangenciales)
que enfrentan hoy los organismos públicos Nacionales y Provinciales en materia tecnológica (Interior y
Transporte, Trabajo, Industria,
…) con el fin de ponerlos a disposición del ingenio de los programadores que
viajaran en del tren. De esta forma, se espera detectar
buenos programadores y poder usar ideas novedosas para mejorar las
instituciones públicas.

En cada parada del tren se realizarán actividades orientadas a la
comunicación tomando como eje la Ley de servicios audiovisuales y la
potencialidad del Software Libre.

Durante todo el recorrido se ira trabajando sobre el material audiovisual
generado en el Hackatren

** Actividades en estaciones
Se utilizará la llegada del tren a cada Ciudad /pueblo para realizar en la estación
misma una intervención del tipo tecnológica o artistica. La misma oficiará
de cierre de una capacitación previa realizada por el equipo auxiliar del
Hackatren previo a la llegada del Tren.
Se realizará un trabajo previo para trabajar con las radios y canales de
cada estación poniendo el eje en difundir las experiencias locales con eje
en la importancia del tren para la vida social de la población local.

*** microcine bacua
Se propone la proyección de contenidos audiovisuales con licencia libre
teniendo particular enfoque en la integración nacional.

*** armar una radio en 2h
en un taller accelerado, en 5 equipos, se recorreran los conocimientos
necesarios para el armado de una radio comunitaria.

Estos talleres se basaran sobre los manuales de la CNC y vendran acompañados
de los mismos tanto como de un DVD de contenidos y otra de programas
necesarios a la tarea.

*** armar un canal de television en 2h
en un taller accelerado, en 5 equipos, se recorrera los conocimientos
necesarios para el armado de una televisión comunitaria.

Estos talleres se basaran en la experiencia del proyecto malbec Broadcast en el
canal Wall KinTun y contara con asistencia de Metropolis Films en lo que
hace a conocimientos básicos de manejo  de cámara y técnicas de filmación.


*** introducción a la programación
Talleres acelerados para tener un primer acercamiento a la programación. Los
mismos estarán a cargo de FACTTIC (Federación Argentina de Cooperativas de Trabajo de Tecnología, Innovación y Conocimiento)
Evaluar sumar a Educ.ar y Program.ar
*** charlas/debates
Se propone usar un espacio del tren como catalyzador de debates.
Se contempla que de este espacio participen autoridades nacionales,
provinciales y municipales.

*** Presencia de Universidades Nacionales
Las Universidades Nacionales que estén en un radio de cercanía con alguna de
las estaciones donde el Tren realice actividades participarán de las mismas
aportando sus producciones de manera de dar a conocer el trabajo de las
mismas y acercarlas a la población.
** Actividad en Buenos Aires

** Actividad en Bariloche
Se realizará una actividad de indole cultural para celebrar la llegada del
tren en la que participaran artistas locales junto al equipo del Hackatren y
los participantes para celebrar el regreso del tren y destacar lo realizado
en el hackaton

** Cierre final
Se realizará o bien en Bariloche o en alguna de las estaciones del tren
cuando este realice el trayecto Bariloche — Buenos Aires. (recomendamos que
la misma no se realice en CABA para no caer en centralismo.) En la misma se
presentarán las solucione desarrolladas durante el viaje y se emitirá parte
del material audiovisual generado en el viaje en la línea de trabajo El Tren
nos conecta y potencia-


* Logistica 
** Tren
En el tren se contará con soporte eléctrico para los equipos informáticos,
routers 3G, y un catering básico que contemple gestionar las comidas de los
participantes y del equipo.

** Equipo auxiliar
Se usará un equipo auxiliar para realizar talleres y capacitaciones previo a
la llegada del tren. este equipo se movilizara en dos vehiculos del tipo
mini bus para ocuparse de tareas de campo previas a la llegada del tren o de
traslado de los participantes del Hackatren que se hubieran quedado en una
estación para realizar una actividad puntual.

** Traslados
se considerará contar con transporte para permitir que desarroladores/as que
no vivan cerca de una estación del recorrido puedan subirse al Hackatren en
Constitución o cualquier otro punto de parada.
